const Constants = {
  NEW_TASK_CREATED: "NEW_TASK_CREATED",
  LIST_ALL_TASKS: "LIST_ALL_TASKS",
  NEW_USER_CREATED: "NEW_USER_CREATED",
  USER_LISTED: "USER_LISTED",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  TOGGLE_SIDE_BAR: "TOGGLE_SIDE_BAR",
  TOKEN_VALID: "TOKEN_VALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  NOTE_ADDED: "NOTE_ADDED"
};

export default Constants;
